---
title: "CarTransLateRej- Clinical Phenotypes"
author: "I. Hanka"
date: "2025-07-02"
output: html_document
---
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages, warning=FALSE, include=FALSE}
#library(ExploreSCdataSeurat3)
#library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
library(future)
library(workflowr)
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/CarTransLateRej/data/CarTransLateRej_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)

#Define Output Pathway
#output_path <- "/Users/immbio/Desktop/CarTransLateRej/analysis/"
```

##set color vectors 
```{r }
### Patient
HH_1 <- c("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM")
HH_3 <- c("o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM")
HH_4 <- c("o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM")
HH_5 <- c("o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM")
HH_6 <- c("o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM")
HH_7 <- c("o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM")
HH_8 <- c("o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM")
HH_9 <- c("o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM")
HH_10 <- c("o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM")
HH_11 <- c("o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM")

seuratM$patient <- "pat_nr"
seuratM$patient[grepl("HTx002|EMB002", seuratM$dataset)] <- "CarTransPat2"
seuratM$patient[grepl("HTx004|EMB004", seuratM$dataset)] <- "CarTransPat4"
seuratM$patient[grepl("HTx006|EMB006", seuratM$dataset)] <- "CarTransPat6"
seuratM$patient[grepl("HTx007|EMB007", seuratM$dataset)] <- "CarTransPat7"
seuratM$patient[grepl("HTx008|EMB008", seuratM$dataset)] <- "CarTransPat8"
seuratM$patient[grepl("HTx018|EMB0018", seuratM$dataset)] <- "CarTransPat18"
seuratM$patient[grepl("HTx019|EMB0019", seuratM$dataset)] <- "CarTransPat19"
seuratM$patient[which(seuratM$dataset %in% HH_1)] <- "HH1"
seuratM$patient[which(seuratM$dataset %in% HH_3)] <- "HH3"
seuratM$patient[which(seuratM$dataset %in% HH_4)] <- "HH4"
seuratM$patient[which(seuratM$dataset %in% HH_5)] <- "HH5"
seuratM$patient[which(seuratM$dataset %in% HH_6)] <- "HH6"
seuratM$patient[which(seuratM$dataset %in% HH_7)] <- "HH7"
seuratM$patient[which(seuratM$dataset %in% HH_8)] <- "HH8"
seuratM$patient[which(seuratM$dataset %in% HH_9)] <- "HH9"
seuratM$patient[which(seuratM$dataset %in% HH_10)] <- "HH10"
seuratM$patient[which(seuratM$dataset %in% HH_11)] <- "HH2"
table(seuratM$patient)

ordpatients <- c("HH1", "HH2", "HH3", "HH4", "HH5", "HH6", "HH7", "HH8", "HH9", "HH10","CarTransPat2", "CarTransPat4", "CarTransPat6", "CarTransPat7", "CarTransPat8", "CarTransPat18", "CarTransPat19")

### DiseaseCond
seuratM$diseaseCond <- "diseaseCond"
seuratM$diseaseCond[grepl("V1", seuratM$dataset)] <- "visit1"
seuratM$diseaseCond[grepl("V2", seuratM$dataset)] <- "visit2"
seuratM$diseaseCond[grepl("V3", seuratM$dataset)] <- "visit3"
seuratM$diseaseCond[grepl("V4", seuratM$dataset)] <- "visit4"
seuratM$diseaseCond[grepl("V5", seuratM$dataset)] <- "visit5"
seuratM$diseaseCond[grepl("VX1", seuratM$dataset)] <- "visitX1"
seuratM$diseaseCond[grepl("VX2", seuratM$dataset)] <- "visitX2"
seuratM$diseaseCond[grepl("VX3", seuratM$dataset)] <- "visitX3"
seuratM$diseaseCond[grepl("VX4", seuratM$dataset)] <- "visitX4"
seuratM$diseaseCond[grepl("HH", seuratM$dataset)] <- "healthy"
orddiseaseCond <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4")

## Cluster Name
seuratM$clusterName <- "clusterName"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "0" )] <- "Fb1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "1" )] <- "PerivFb"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "2" )] <- "BEC1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "3" )] <- "Mph"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "4" )] <- "CM"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "5" )] <- "Tcell"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "6" )] <- "BEC2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "7" )] <- "VSMC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "8" )] <- "Bcell"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "9" )] <- "NC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "10" )] <- "Int1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "11" )] <- "Fb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "12" )] <- "Int2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "13" )] <- "Fb3"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "14" )] <- "AdipoC"


##set color vectors 
colclusterName <- c("#67001f", "#003c30","#01665e","#66C2A5","#355C7D","#202547","#8c510a", "#B09C85", "#628395", "#4e5a4c","pink", "#3299CA", "#725663FF","#B45B5C","#FEE08B")
names(colclusterName) <- c("CM", "Fb1","Fb2","Fb3", "PerivFb","VSMC", "BEC1", "BEC2", "Bcell", "NC", "Int1", "Int2", "AdipoC", "Mph", "Tcell")

coldiseaseCond <- c("#dfc27d","#BE3144","#f4a582","#B45B5C","#8c510a","#202547","#355C7D","#779d8d", "#3288BD", "#BEAED4")
names(coldiseaseCond) <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4")
```


#########PATHOLOGY GRADING##############
```{r Order corresponding to pathological grading}

Healthy <-c ("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM",
             "o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM",
             "o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM",
             "o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM",
             "o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM",
             "o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM",
             "o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM",
             "o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM",
             "o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM",
             "o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM")

ACR0 <- c ("336431_11-11_20231129_Hu_nucseq_USZ_EMB006_V1",
           "340821_09-15_20240123_Hu_nucseq_USZ_EMB007_V3",
           "384091_10-10_20250423_Hu_nucseq_USZ_HTx008_VX3",
           "336431_12-12_20231129_Hu_nucseq_USZ_EMB007_V1",
           "340821_06-12_20240123_Hu_nucseq_USZ_EMB004_V3",
           "373291_21-13_20241212_Hu_nucseq_USZ_HTx004_V4",
           "340821_08-14_20240123_Hu_nucseq_USZ_EMB006_V3",
           "340831_6-6_20240118_Hu_nucseq_USZ_EMB006_V2")

ACR1R <- c("340821_01-7_20240118_Hu_nucseq_USZ_EMB007_V2",
           "373291_09-1_20241212_Hu_nucseq_USZ_HTx006_V4",
           "373291_12-4_20241212_Hu_nucseq_USZ_HTx006_VX2",
           "373291_20-12_20241212_Hu_nucseq_USZ_HTx018_VX1",
           "384091_04-4_20250423_Hu_nucseq_USZ_HTx019_VX1",
           "340831_4-4_20240118_Hu_nucseq_USZ_EMB004_V2",
           "372561_09-9_20241204_Hu_nucseq_USZ_HTx004_VX2",
           "373291_10-2_20241212_Hu_nucseq_USZ_HTx006_V5",
           "373291_13-5_20241212_Hu_nucseq_USZ_HTx006_VX3",
           "373291_18-10_20241212_Hu_nucseq_USZ_HTx018_V3",
           "384091_05-5_20250423_Hu_nucseq_USZ_HTx002_VX2",
           "384091_11-11_20250423_Hu_nucseq_USZ_HTx018_VX2",
           "336431_15-15_20231129_Hu_nucseq_USZ_EMB004_V1",
           "372561_13-13_20241204_Hu_nucseq_USZ_HTx007_V5",
           "373291_16-8_20241212_Hu_nucseq_USZ_HTx018_V1",
           "373291_22-14_20241212_Hu_nucseq_USZ_HTx004_V5",
           "384091_03-3_20250423_Hu_nucseq_USZ_HTx019_V3",
           "384091_06-6_20250423_Hu_nucseq_USZ_HTx002_VX3")

ACR2R <- c("372561_08-8_20241204_Hu_nucseq_USZ_HTx004_VX1",
           "372561_11-11_20241204_Hu_nucseq_USZ_HTx007_VX1",
           "373291_17-9_20241212_Hu_nucseq_USZ_HTx018_V2",
           "384091_01-1_20250423_Hu_nucseq_USZ_HTx019_V1",
           "384091_07-7_20250423_Hu_nucseq_USZ_HTx007_VX3",
           "372561_12-12_20241204_Hu_nucseq_USZ_HTx007_VX2",
           "384091_08-8_20250423_Hu_nucseq_USZ_HTx007_VX4",
           "373291_11-3_20241212_Hu_nucseq_USZ_HTx006_VX1",
           "373291_19-11_20241212_Hu_nucseq_USZ_HTx018_V4",
           "384091_09-9_20250423_Hu_nucseq_USZ_HTx008_VX2")

ACR3R <- c("384091_02-2_20250423_Hu_nucseq_USZ_HTx019_V2",
           "372561_10-10_20241204_Hu_nucseq_USZ_HTx007_V4")

seuratM$pat_patho <- "pat_patho"
seuratM$pat_patho[which(seuratM$dataset %in% Healthy) ] <- "Healthy"
seuratM$pat_patho[which(seuratM$dataset %in% ACR0) ] <- "ACR0"
seuratM$pat_patho[which(seuratM$dataset %in% ACR1R) ] <- "ACR1R"
seuratM$pat_patho[which(seuratM$dataset %in% ACR2R) ] <- "ACR2R"
seuratM$pat_patho[which(seuratM$dataset %in% ACR3R) ] <- "ACR3R"

ordpat_patho <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
```

```{r}
cell_count <- data.frame(table(seuratM$pat_patho))
#view(cell_count)
colnames(cell_count) <- c ("Pathology", "Freq")
hsize <- 1.5

ggplot(cell_count, aes(x=hsize, y=Freq, fill = Pathology)) +
  geom_col(color="white") +
  coord_polar(theta = "y") +
  xlim (c(0.2, hsize + 0.5)) +
  theme_void() +
  ggtitle ("Cell Number") +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  geom_text(aes(label = Freq), position = position_stack(vjust = 0.5))
```


```{r}
Idents(seuratM) <- seuratM$pat_patho
colpat_patho <- c("#dfc27d","lightgrey","lightgrey","lightgrey","lightgrey")
names(colpat_patho) <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colpat_patho, order = "Healthy") 

colpat_patho <- c("lightgrey","#BE3144","lightgrey","lightgrey","lightgrey")
names(colpat_patho) <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colpat_patho, order = "ACR0") 

colpat_patho <- c("lightgrey","lightgrey","#f4a582","lightgrey","lightgrey")
names(colpat_patho) <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colpat_patho, order = "ACR1R") 

colpat_patho <- c("lightgrey","lightgrey","lightgrey","#B45B5C","lightgrey")
names(colpat_patho) <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colpat_patho, order = "ACR2R")

colpat_patho <- c("lightgrey","lightgrey","lightgrey","lightgrey", "#8c510a")
names(colpat_patho) <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colpat_patho, order = "ACR3R")


colpat_patho <- c("#dfc27d","#BE3144","#f4a582","#B45B5C","#8c510a")
```

```{r}
#Relative Abundances

datList <- NULL
for(con in unique(seuratM$pat_patho)){
  seuratSub <- subset(seuratM, pat_patho==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

ordpat_patho <- c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")

## plot abundance
ggbarplot(dat_all, x= "diseaseCond", y= "percent", fill = "Var1", legend = "right",  palette = colclusterName, legend.titel = "pathology", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpat_patho)
```
```{r}
#Heat Map Pathology using cluster genes
Idents(seuratM) <- seuratM$pat_patho
                            
genes <- data.frame(gene=rownames(seuratM)) %>% 
  mutate(geneID=gsub("^.*\\.", "", gene))

selGenes <- data.frame(geneID=rev(c("TTN", "MYBPC3", "RYR2", "NEBL", "TNNT2", "CMYA5", "COL6A3", "DCN",  "FBN1", "C7", "PDGFRA", "CDH19", "PDGFRB","ITGA7","RGS5", "NOTCH3", "MYH11", "ACTA2","PECAM1", "VWF", "EGFL7", "POSTN", "ITGA10", "CDH11","CCL21", "PROX1", "FLT4", "NRXN1", "ANK3", "PTPRZ1", "ACACB", "PLIN1", "GPAM", "CD163", "MRC1", "SIGLEC1", "STAB1", "CSF1R", "MERTK", "IL7R", "PTPRC", "CD2", "PAX5", "IGHM", "IGKC", "MS4A1"))) %>% left_join(., genes, by="geneID") %>% filter(gene != "ENSG00000232995.RGS5") 

seurat <- seuratM

avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  selGenes <- selGenes$gene
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                     colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
   dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
   dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      celltype=colVec)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
  ordVec <- levels(seurat)
  ordVec <-c("Healthy", "ACR0", "ACR1R" ,"ACR2R", "ACR3R")
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0,cluster_rows = cr, 
         cluster_cols = cc, color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = NULL, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

genesPlot <- data.frame(gene=c("TTN", "MYBPC3", "RYR2", "NEBL", "TNNT2", "CMYA5", "COL6A3", "DCN",  "FBN1", "C7", "PDGFRA", "CDH19", "PDGFRB","ITGA7","RGS5", "NOTCH3", "MYH11", "ACTA2","PECAM1", "VWF", "EGFL7", "POSTN", "ITGA10", "CDH11","CCL21", "PROX1", "FLT4", "NRXN1", "ANK3", "PTPRZ1", "ACACB", "PLIN1", "GPAM", "CD163", "MRC1", "SIGLEC1", "STAB1", "CSF1R", "MERTK", "IL7R", "PTPRC", "CD2", "PAX5", "IGHM", "MS4A1", "IGKC"))

levels(seurat)
colVec <- colpat_patho
avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)

#pdf(file.path(output_path,"Heatmap_ACR.pdf"), height = 20, width = 8)
#avgHeatmap(seurat, selGenes = genesPlot, colVecIdent = colVec)
#dev.off()
```


########Sex######
```{r}
#Allocate Biopsies to sex

female <- c ("340821_06-12_20240123_Hu_nucseq_USZ_EMB004_V3",
           "373291_21-13_20241212_Hu_nucseq_USZ_HTx004_V4",
           "373291_20-12_20241212_Hu_nucseq_USZ_HTx018_VX1",
           "384091_04-4_20250423_Hu_nucseq_USZ_HTx019_VX1",
           "340831_4-4_20240118_Hu_nucseq_USZ_EMB004_V2",
           "372561_09-9_20241204_Hu_nucseq_USZ_HTx004_VX2",
           "373291_18-10_20241212_Hu_nucseq_USZ_HTx018_V3",
           "384091_11-11_20250423_Hu_nucseq_USZ_HTx018_VX2",
           "336431_15-15_20231129_Hu_nucseq_USZ_EMB004_V1",
           "373291_16-8_20241212_Hu_nucseq_USZ_HTx018_V1",
           "373291_22-14_20241212_Hu_nucseq_USZ_HTx004_V5",
           "384091_03-3_20250423_Hu_nucseq_USZ_HTx019_V3",
           "372561_08-8_20241204_Hu_nucseq_USZ_HTx004_VX1",
           "373291_17-9_20241212_Hu_nucseq_USZ_HTx018_V2",
           "384091_01-1_20250423_Hu_nucseq_USZ_HTx019_V1",
           "373291_19-11_20241212_Hu_nucseq_USZ_HTx018_V4",
           "384091_02-2_20250423_Hu_nucseq_USZ_HTx019_V2")

male <- c ("340821_01-7_20240118_Hu_nucseq_USZ_EMB007_V2",
           "336431_11-11_20231129_Hu_nucseq_USZ_EMB006_V1",
           "340821_09-15_20240123_Hu_nucseq_USZ_EMB007_V3",
           "384091_10-10_20250423_Hu_nucseq_USZ_HTx008_VX3",
           "336431_12-12_20231129_Hu_nucseq_USZ_EMB007_V1",
           "340821_08-14_20240123_Hu_nucseq_USZ_EMB006_V3",
           "340831_6-6_20240118_Hu_nucseq_USZ_EMB006_V2",
           "373291_09-1_20241212_Hu_nucseq_USZ_HTx006_V4",
           "373291_12-4_20241212_Hu_nucseq_USZ_HTx006_VX2",
           "373291_10-2_20241212_Hu_nucseq_USZ_HTx006_V5",
           "373291_13-5_20241212_Hu_nucseq_USZ_HTx006_VX3",
           "384091_05-5_20250423_Hu_nucseq_USZ_HTx002_VX2",
           "372561_13-13_20241204_Hu_nucseq_USZ_HTx007_V5",
           "384091_06-6_20250423_Hu_nucseq_USZ_HTx002_VX3",
           "372561_11-11_20241204_Hu_nucseq_USZ_HTx007_VX1",
           "384091_07-7_20250423_Hu_nucseq_USZ_HTx007_VX3",
           "372561_12-12_20241204_Hu_nucseq_USZ_HTx007_VX2",
           "384091_08-8_20250423_Hu_nucseq_USZ_HTx007_VX4",
           "373291_11-3_20241212_Hu_nucseq_USZ_HTx006_VX1",
           "384091_09-9_20250423_Hu_nucseq_USZ_HTx008_VX2",
           "372561_10-10_20241204_Hu_nucseq_USZ_HTx007_V4")

unknown <- c ("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM",
             "o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM",
             "o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM",
             "o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM",
             "o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM",
             "o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM",
             "o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM",
             "o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM",
             "o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM",
             "o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM")
      
seuratM$sex <- "sex"
seuratM$sex[which(seuratM$dataset %in% female)] <- "female"
seuratM$sex[which(seuratM$dataset %in% male)] <- "male"
seuratM$sex[which(seuratM$dataset %in% unknown)] <- "unknown"
```

```{r}
cell_count <- data.frame(table(seuratM$sex))
#view(cell_count)
colnames(cell_count) <- c ("sex", "Freq")
hsize <- 1.5

ggplot(cell_count, aes(x=hsize, y=Freq, fill = sex)) +
  geom_col(color="white") +
  coord_polar(theta = "y") +
  xlim (c(0.2, hsize + 0.5)) +
  theme_void() +
  ggtitle ("Cell Number") +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  geom_text(aes(label = Freq), position = position_stack(vjust = 0.5))
```

