---
title: "CarTransLateRej - RelativeAbundances"
author: "I. Hanka"
date: "2025-05-23"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---
## load packages
```{r load packages, warning=FALSE, include=FALSE}
#library(ExploreSCdataSeurat3)
#library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/CarTransLateRej/data/CarTransLateRej_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
```

##set color vectors 
```{r }
### patient
HH_1 <- c("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM")
HH_3 <- c("o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM")
HH_4 <- c("o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM")
HH_5 <- c("o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM")
HH_6 <- c("o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM")
HH_7 <- c("o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM")
HH_8 <- c("o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM")
HH_9 <- c("o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM")
HH_10 <- c("o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM")
HH_11 <- c("o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM")

seuratM$patient <- "pat_nr"
seuratM$patient[grepl("HTx002|EMB002", seuratM$dataset)] <- "CarTransPat2"
seuratM$patient[grepl("HTx004|EMB004", seuratM$dataset)] <- "CarTransPat4"
seuratM$patient[grepl("HTx006|EMB006", seuratM$dataset)] <- "CarTransPat6"
seuratM$patient[grepl("HTx007|EMB007", seuratM$dataset)] <- "CarTransPat7"
seuratM$patient[grepl("HTx008|EMB008", seuratM$dataset)] <- "CarTransPat8"
seuratM$patient[grepl("HTx018|EMB0018", seuratM$dataset)] <- "CarTransPat18"
seuratM$patient[grepl("HTx019|EMB0019", seuratM$dataset)] <- "CarTransPat19"
seuratM$patient[which(seuratM$dataset %in% HH_1)] <- "HH1"
seuratM$patient[which(seuratM$dataset %in% HH_3)] <- "HH3"
seuratM$patient[which(seuratM$dataset %in% HH_4)] <- "HH4"
seuratM$patient[which(seuratM$dataset %in% HH_5)] <- "HH5"
seuratM$patient[which(seuratM$dataset %in% HH_6)] <- "HH6"
seuratM$patient[which(seuratM$dataset %in% HH_7)] <- "HH7"
seuratM$patient[which(seuratM$dataset %in% HH_8)] <- "HH8"
seuratM$patient[which(seuratM$dataset %in% HH_9)] <- "HH9"
seuratM$patient[which(seuratM$dataset %in% HH_10)] <- "HH10"
seuratM$patient[which(seuratM$dataset %in% HH_11)] <- "HH2"
table(seuratM$patient)

ordpatients <- c("HH1", "HH2", "HH3", "HH4", "HH5", "HH6", "HH7", "HH8", "HH9", "HH10","CarTransPat2", "CarTransPat4", "CarTransPat6", "CarTransPat7", "CarTransPat8", "CarTransPat18", "CarTransPat19")

seuratM$clusterName <- "clusterName"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "0" )] <- "Fb1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "1" )] <- "PerivFb"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "2" )] <- "BEC1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "3" )] <- "Mph"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "4" )] <- "CM"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "5" )] <- "Tcell"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "6" )] <- "BEC2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "7" )] <- "VSMC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "8" )] <- "Bcell"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "9" )] <- "NC"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "10" )] <- "Int1"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "11" )] <- "Fb2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "12" )] <- "Int2"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "13" )] <- "Fb3"
seuratM$clusterName[which(seuratM$RNA_snn_res.0.25 %in% "14" )] <- "AdipoC"


##set color vectors 
colclusterName <- c("#67001f", "#003c30","#01665e","#66C2A5","#355C7D","#202547","#8c510a", "#B09C85", "#628395", "#4e5a4c","pink", "#3299CA", "#725663FF","#B45B5C","#FEE08B")
names(colclusterName) <- c("CM", "Fb1","Fb2","Fb3", "PerivFb","VSMC", "BEC1", "BEC2", "Bcell", "NC", "Int1", "Int2", "AdipoC", "Mph", "Tcell")

coldiseaseCond <- c("#dfc27d","#BE3144","#f4a582","#B45B5C","#8c510a","#202547","#355C7D","#779d8d", "#3288BD", "#BEAED4")
names(coldiseaseCond) <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4")
```

## order datasets
```{r order, include=FALSE}
Idents(seuratM) <- seuratM$clusterName
seuratM$clusterName <- factor(seuratM$clusterName, levels=c("CM", "Fb1","Fb2","Fb3", "PerivFb","VSMC", "BEC1", "BEC2", "Bcell", "NC", "Int1", "Int2", "AdipoC", "Mph", "Tcell"))
Idents(seuratM) <- seuratM$clusterName
table(seuratM$clusterName)

seuratM$diseaseCond <- "diseaseCond"
seuratM$diseaseCond[grepl("V1", seuratM$dataset)] <- "visit1"
seuratM$diseaseCond[grepl("V2", seuratM$dataset)] <- "visit2"
seuratM$diseaseCond[grepl("V3", seuratM$dataset)] <- "visit3"
seuratM$diseaseCond[grepl("V4", seuratM$dataset)] <- "visit4"
seuratM$diseaseCond[grepl("V5", seuratM$dataset)] <- "visit5"
seuratM$diseaseCond[grepl("VX1", seuratM$dataset)] <- "visitX1"
seuratM$diseaseCond[grepl("VX2", seuratM$dataset)] <- "visitX2"
seuratM$diseaseCond[grepl("VX3", seuratM$dataset)] <- "visitX3"
seuratM$diseaseCond[grepl("VX4", seuratM$dataset)] <- "visitX4"
seuratM$diseaseCond[grepl("HH", seuratM$dataset)] <- "healthy"
seuratM$diseaseCond <- factor(seuratM$diseaseCond, levels=c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4"))
Idents(seuratM) <- seuratM$diseaseCond
table(seuratM$diseaseCond)
```

```{r abundance diseaseCond, fig.height=8, fig.width=10}
###diseaseCond
datList <- NULL
for(con in unique(seuratM$diseaseCond)){
  seuratSub <- subset(seuratM, diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

orddiseaseCond <- c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4")

## plot abundance
ggbarplot(dat_all, x= "diseaseCond", y= "percent", fill = "Var1", legend = "right",  palette = colclusterName, legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=orddiseaseCond)
```

```{r abundance patient_diseaseCond, fig.height=8, fig.width=10}
###patient_diseaseCond
seuratM$patient_diseaseCond <- paste0(seuratM$patient, '_', seuratM$diseaseCond)
datList <- NULL
for(con in unique(seuratM$patient_diseaseCond)){
  seuratSub <- subset(seuratM, patient_diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$clusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(patient_diseaseCond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

ordpatient_diseasecond <- unique(seuratM$patient_diseaseCond)[order(
  !grepl("healthy", unique(seuratM$patient_diseaseCond)),  # "HH" first (FALSE is sorted before TRUE)
  !grepl("visit1", unique(seuratM$patient_diseaseCond)),  # "visit1" second
  !grepl("visit2", unique(seuratM$patient_diseaseCond)),  # "visit2" third
  !grepl("visit3", unique(seuratM$patient_diseaseCond)),  # "visit3" forth
  !grepl("visit4", unique(seuratM$patient_diseaseCond)),  # "visit4" fifth
  !grepl("visit5", unique(seuratM$patient_diseaseCond)),  # "visit5" sixth
  !grepl("visitX1", unique(seuratM$patient_diseaseCond)),  # "visitX1" seventh
  !grepl("visitX2", unique(seuratM$patient_diseaseCond)),  # "visitX2" eighth
   !grepl("visitX3", unique(seuratM$patient_diseaseCond)),  # "visitX3" ninth
  !grepl("visitX4", unique(seuratM$patient_diseaseCond)),  # "visitX4" tenth
  unique(seuratM$patient_diseaseCond)  # Alphabetical order within groups
)]

## plot abundance
ggbarplot(dat_all, x= "patient_diseaseCond", y= "percent", fill = "Var1", palette = colclusterName, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpatient_diseasecond)


ordpatient_diseasecond <- unique(seuratM$patient_diseaseCond)[order(
  !grepl("healthy", unique(seuratM$patient_diseaseCond)),  # "HH" first (FALSE is sorted before TRUE)
  !grepl("CarTransPat4", unique(seuratM$patient_diseaseCond)),  # CarTransPat4 second
  !grepl("CarTransPat6", unique(seuratM$patient_diseaseCond)),
  !grepl("CarTransPat7", unique(seuratM$patient_diseaseCond)),
  !grepl("CarTransPat18", unique(seuratM$patient_diseaseCond)),  
  unique(seuratM$patient_diseaseCond)  # Alphabetical order within groups
)]

## plot abundance
ggbarplot(dat_all, x= "patient_diseaseCond", y= "percent", fill = "Var1", palette = colclusterName, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(limits=ordpatient_diseasecond)
```

## fractions according to patients&disease cond
```{r fractions, fig.height=8, fig.width=10}
##set order
seuratM$diseaseCond <- factor(seuratM$diseaseCond, levels= c("healthy", "visit1", "visit2" ,"visit3", "visit4", "visit5", "visitX1", "visitX2", "visitX3", "visitX4"))

## 1. create data.frame with cluster counts per patient
## change "RNA_snn_res.0.25" to subset/cluster you're interested in ...
datFrac <- data.frame(table(seuratM$patient_diseaseCond, seuratM$clusterName))
colnames(datFrac) <- c("patient_diseaseCond", "subset", "cnt")

## 2. get total counts per patient to compute relative abundances from
## I added cond here as grouping variable for the plotting later ...
datSumPat <- data.frame(table(seuratM$patient_diseaseCond, seuratM$diseaseCond)) %>% 
  filter(Freq >0)
colnames(datSumPat) <- c("patient_diseaseCond", "diseaseCond", "cntPatTot")

## 3. join data.frames to compute rel abundances per patient
datFracSum <- datFrac %>% left_join(., datSumPat, by = "patient_diseaseCond") %>% 
  mutate(relCnt = cnt/cntPatTot)

## plot barplot with abundances for each subset grouped by cond
ggbarplot(datFracSum, x = "subset", y = "relCnt",
          fill = "diseaseCond", color = "diseaseCond",
          palette = coldiseaseCond,
          add = c("mean_se", "dotplot"),
          add.params = list(color="black", fill="diseaseCond", size=0.2),
          position = position_dodge(0.9),
          xlab = "subset",
          ylab = "relative abundance",
          legend = "right",
          legend.title = "") +
  rotate_x_text(angle = 90) 

## plot barplot with abundances for individual subsets
Idents(seuratM) <- seuratM$clusterName
clusterVec <- levels(seuratM)
createClusterPlot <- function(cluster) {
  datFracSumC <- datFracSum %>% filter(subset == cluster)

  ggbarplot(datFracSumC, x = "diseaseCond", y = "relCnt",
            fill = "diseaseCond", color = "diseaseCond",
            palette = coldiseaseCond,
            add = c("mean_se", "dotplot"),
            size = 5,
            add.params = list(color = "black", fill = "diseaseCond"),
            position = position_dodge(0.9),
            xlab = cluster,
            ylab = "relative abundance",
            legend = "right",
            legend.title = "") +
    stat_compare_means(method = "kruskal.test", label.y = 0.0)
}
lapply(clusterVec, createClusterPlot)
```

```{r}
#Show total counts

seuratM$patient_diseaseCond_cluster <- paste0(seuratM$patient, '_', seuratM$diseaseCond, '_', seuratM$clusterName)
TableClusterPatientDis <- table(seuratM$patient_diseaseCond_cluster)
#View(TableClusterPatientDis)
dfClusterPatDis <- as.data.frame(TableClusterPatientDis)

sub_Tcells <- dfClusterPatDis[grep("_Tcell", dfClusterPatDis$Var1),]
show(sub_Tcells)
```



## session info
```{r date and session info}
date()
sessionInfo()
```
